# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08tx.proto\x12\x02tx\"3\n\x0b\x41\x63\x63\x65ssTuple\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x13\n\x0bstorageKeys\x18\x02 \x03(\t\"\xad\x02\n\x0bTransaction\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x15\n\x08gasPrice\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x0b\n\x03gas\x18\x05 \x01(\x04\x12\x19\n\x0cmaxFeePerGas\x18\x06 \x01(\tH\x01\x88\x01\x01\x12!\n\x14maxPriorityFeePerGas\x18\x07 \x01(\tH\x02\x88\x01\x01\x12\r\n\x05nonce\x18\x08 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\t\x12#\n\naccessList\x18\n \x03(\x0b\x32\x0f.tx.AccessTuple\x12\x18\n\x04type\x18\x0b \x01(\x0e\x32\n.tx.TxTypeB\x0b\n\t_gasPriceB\x0f\n\r_maxFeePerGasB\x17\n\x15_maxPriorityFeePerGas*5\n\x06TxType\x12\n\n\x06LEGACY\x10\x00\x12\x0e\n\nAccessList\x10\x01\x12\x0f\n\x0b\x44YNAMIC_FEE\x10\x02\x42\x04Z\x02txb\x06proto3')

_TXTYPE = DESCRIPTOR.enum_types_by_name['TxType']
TxType = enum_type_wrapper.EnumTypeWrapper(_TXTYPE)
LEGACY = 0
AccessList = 1
DYNAMIC_FEE = 2


_ACCESSTUPLE = DESCRIPTOR.message_types_by_name['AccessTuple']
_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
AccessTuple = _reflection.GeneratedProtocolMessageType('AccessTuple', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSTUPLE,
  '__module__' : 'tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.AccessTuple)
  })
_sym_db.RegisterMessage(AccessTuple)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002tx'
  _TXTYPE._serialized_start=373
  _TXTYPE._serialized_end=426
  _ACCESSTUPLE._serialized_start=16
  _ACCESSTUPLE._serialized_end=67
  _TRANSACTION._serialized_start=70
  _TRANSACTION._serialized_end=371
# @@protoc_insertion_point(module_scope)
